config/routes.rb
Rails.application.routes.draw do
  get 'little/Havana'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pictures#index', page: 1
  # get 'gallery' => 'gallery#gallery'
  get 'pictures', to: 'pictures#index', page: 1
  get 'pictures/page/:page', to: 'pictures#index'
  get 'pictures/:id/liked' => 'pictures#liked'

  resources :brickell
  resources :south_beach
  resources :little_havana
  resources :wynwood
  resources :pictures
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
validates :image, presence: true

has_attached_file :image, styles: { :medium => "640px" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brickell_controller.rb
class BrickellController < ApplicationController
  def index
    render :brickell
  end
end

app/controllers/little_havana_controller.rb
class LittleHavanaController < ApplicationController
  def index
    render :little_havana
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]


  def index
    @page = params[:page].to_i || 1
    skip = (@page - 1) * 5
    @pictures = Picture.all.order(created_at: :desc).limit(5).offset(skip)
  end

  def show
  end

  def create
    @picture = Picture.create(picture_params)
    redirect_to pictures_path
  end

  def edit
  end

  def destroy
    @pictures.destroy
    redirect_to root_path
  end

  def update
    if @pictures.update(picture_params)
      redirect_to(picture_path(@pictures))
    else
      render :edit
    end
  end

  def new
    @picture = Picture.new
  end

  def liked
    @picture = Picture.find(params[:id])
    @picture.likes += 1
    if @picture.save
      render :nothing => true, :status => 200
    else
      render :nothing => true, :status => 500
    end
  end

  private

  def picture_params
    params.require(:picture).permit(:image, :caption)
  end

  def set_picture
    @pictures = Picture.find(params[:id])
  end

end

app/controllers/south_beach_controller.rb
class SouthBeachController < ApplicationController
  def index
    render :south_beach
  end
end

app/controllers/wynwood_controller.rb
class WynwoodController < ApplicationController
  def index
    render :wynwood
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brickell_helper.rb
module BrickellHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/little_havana_helper.rb
module LittleHavanaHelper
end

app/helpers/little_helper.rb
module LittleHelper
end

app/helpers/neighborhood_helper.rb
module NeighborhoodHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/south_beach_helper.rb
module SouthBeachHelper
end

app/helpers/wynwood_helper.rb
module WynwoodHelper
end

app/views/brickell/brickell.html.erb
<!-- DOCTYPE -->
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Miami's Downtown</title>
  <!-- Required meta tags always come first -->
  <meta charset="utf-8">
  <meta name="author" content="Sam Norton">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="css/bootstrap.min.css">
  <link rel="stylesheet" href="css/custom.css">
  <!-- Fonts -->
  <link href='https://fonts.googleapis.com/css?family=Lato:400,700,900,300' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,300,600,700,900' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>

<body>
  <section class="brickell parallax parallax-1">
    <div class="container">
      <h1>iconic Brickell</h1>
    </div>
  </section>


  <section class="brickell content">
    <div class="content">
      <div class="row">
        <div class="col-md-3">
          <div class="card">
            <img class="card-img-top" src="/rsz_shopping.jpg" alt="Cuban Food">
            <div id="bootstrap-brickell-overrides">
              <div class="card-block">
                <h4 class="card-title">Shopping</h4>
                Get ready to max out your credit cards and lie to your husband about how my that little Gucci dress was because Brickell has one of the HOTTEST shopping scenes in the city. Dont forget to check out where two broke girls like to window shop.
                <br><br><ul>
                  <li><a href="http://brickellcitycentre.com/">Brickell City Center</a></li>
                  <li><a href="http://www.saksfifthavenue.com/Entry.jsp">Saks Fifth Avenue</a></li>
                  <li><a href="http://www.luxymiami.com/">Luxy Miami Boutique</a></li>
                  <li><a href="https://www.yelp.com/biz/atikshop-miami">Atikshop</a></li>
                </ul><br>
                <p>Get the most bang for your buck with other shopping experiences around town.</p>
                <a href="https://www.yelp.com/search?cflt=shopping&find_loc=Brickell%2C+Miami%2C+FL" class="btn btn-primary">See More</a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card card-inverse card-primary text-center">
            <img class="card-img-top" src="/margs.jpg" alt="Cuban Coffee">
            <div id="bootstrap-brickell-overrides">
              <div class="card-block">
                <h4 class="card-title">Happy Hours</h4>
                If there is one thing you should know about me by now, it's that I love a stiff drink after a day of doing nothing but waiting until I can have a stiff drink. Make sure to check out some of our favorite places in Brickell and make sure to tell them Tara and Ariana sent you, you might get a free drink! (or ordered to pay our outstanding tabs!)
                <br><br><ul>
                  <li><a href="http://www.blackbirdordinary.com/">Blackbird Ordinary</a></li>
                  <li><a href="http://americansocialbar.com/brickell/">American Social</a></li>
                  <li><a href="http://www.batchmiami.com/">Batch Gastropub</a></li>
                  <li><a href="http://www.babyjanemiami.com/">Baby Jane</a></li>
                </ul><br>
                <p>Don't was to take our recommendations? Fine, but check out what other local spots are popular.</p>
                <a href="https://www.yelp.com/search?find_desc=Happy+Hour+Brickell&find_loc=Brickell%2C+Miami%2C+FL" class="btn btn-primary">See More</a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card card-inverse card-success text-center">
            <img class="card-img-top" src="/pool.jpg" alt="Dancing">
            <div id="bootstrap-brickell-overrides">
              <div class="card-block">
                <h4 class="card-title">Exclusive Spots</h4>
                Now don't worry, just because you roam around with the common folk, doesn't mean that you can reap the benifits of an exclusive hot spot. We gotchu! But don't tell them we sent you...
                <br><br><ul>
                  <li><a href="http://www.mandarinoriental.com/miami/fine-dining/mo-bar-and-lounge/">Mo Bar & Lounge</a></li>
                  <li><a href="http://www.wmiamihotel.com/miami-nightclub">Whisper Cocktail Lounge</a></li>
                  <li><a href="http://eltucanmiami.com/">El Tucan</a></li>
                  <li><a href="http://www.liltlounge.com/">Lilt Lounge</a></li>
                </ul><br>
                <p>Need more exclusivity? Check out other places people love and make sure to get on the list.</p>
                <a href="https://www.yelp.com/search?cflt=nightlife&find_loc=Brickell%2C+Miami%2C+FL" class="btn btn-primary">See More</a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card card-inverse card-info text-center">
            <img class="card-img-top" src="spot.jpg" alt="Art">
            <div id="bootstrap-brickell-overrides">
              <div class="card-block">
                <h4 class="card-title">Hole in the Wall</h4>
                Nothing make me feel more like a local than telling people about all my favorite hole in the places and assert my hipster superiority over others. Speaking of which, I know some great little holl in the wall places that you will LIVE for!
                <Br><br><ul>
                  <li><a href="http://www.suviche.com/miami-brickell-sushi-ceviche-peruvian-restaurant">SuViche</a></li>
                  <li><a href="http://www.perricones.com/">Perricones</a></li>
                  <li><a href="http://www.piola.it/local-miami-brickell-fl/cities/display">Piola</a></li>
                  <li><a href="http://doloreslolita.com/">Dolores Lolita</a></li>
                </ul><br>
                <p>Want more? Get more.</p>
                <a href="https://www.yelp.com/search?find_desc=famous+hole+in+the+wall+restaurants&start=0&l=g:-80.18530368804932,25.77072369449293,-80.1981782913208,25.75912901955287" class="btn btn-primary">See More</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- JavaScripts -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/tether.min.js"></script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Happenstance | See Your City</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans|Raleway" rel="stylesheet">
  </head>

  <body id="bootstrap-overrides">
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Happenstance</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/pictures/new">Share your finds! <span class="sr-only">(current)</span></a></li>
        <!-- <li><a href="/gallery">Recent</a></li> -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Welcome To Miami <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/wynwood">Wynwood</a></li>
            <li><a href="/south_beach">South Beach</a></li>
            <li><a href="/brickell">Brickell</a></li>
            <li><a href="/little_havana">Little Havana</a></li>
            <!-- <li role="separator" class="divider"></li> -->
            <!-- <li><a href="#">Explore All</a></li> -->
            <!-- <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li> -->
          </ul>
        </li>
      </ul>
      <!-- <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Start your journey...">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form> -->
      <!-- <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul> -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    <%= yield %>
  </body>
</html>

app/views/little_havana/little_havana.html.erb
<!-- DOCTYPE -->
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Littlle Havana</title>
  <!-- Required meta tags always come first -->
  <meta charset="utf-8">
  <meta name="author" content="Sam Norton">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="css/bootstrap.min.css">
  <link rel="stylesheet" href="css/custom.css">
  <!-- Fonts -->
  <link href='https://fonts.googleapis.com/css?family=Lato:400,700,900,300' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Raleway:400,300,600,700,900' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<!-- #body here -->
<body>
  <section class="havana parallax parallax-1">
    <div class="container">
      <h1> Explore Little Havana</h1>
    </div>
  </section>


  <section class="havana content">
    <div class="content">


      <div class="row">
        <div class="col-md-3">
          <div class="card">
            <img class="card-img-top" src="/eatlike.jpg" alt="Cuban Food">
            <div id="boostrap-havana-overrides">
            <div class="card-block">
              <h4 class="card-title">Eat Like a Local</h4>
              <p>Try these gems in Little Havana for authentic Cuban food
                <br>
                <ul>
              <li><a href="http://www.doceprovisions.com/">Doce Provisions</a></li>
              <li><a href="https://ballandchainmiami.com/">Ball & Chain</a></li>
              <li><a href="http://www.littlehavanarestaurant.com/">Little Havana Restaurant</a></p></li>
            </ul>
            <p>Need more? Click here for other foodie spots</p>
            <a href="https://www.yelp.com/search?find_desc=Restaurants&find_loc=Little+Havana,+Miami,+FL" class="btn btn-primary">MORE</a>
          </div>
          </div>
          </div>
        </div>

        <div class="col-md-3">
          <div class="card card-inverse card-primary text-center">
            <img class="card-img-top" src="/cortadito.jpg" alt="Cuban Coffee">
            <div id="boostrap-havana-overrides">
            <div class="card-block">
              <h4 class="card-title">Best Cafecitos</h4>
              If there's something Cubans are known for, it's their delicious cortadito, or "cuban coffee"</br>
              <br>
              <ul>
              <li><a href="https://www.eternitycoffeeroasters.com/">Eternity Coffee Roasters</a></li>
              <li><a href="http://www.versaillesrestaurant.com/">Versailles</a></li>
              <li><a href="http://www.littlehavanarestaurant.com/">Little Havana Restaurant</a></p></li>
            </ul>
            <p>Click here for more options on where to get your coffee fix in Little Havana!</p>
              <a href="https://www.yelp.com/search?find_desc=coffee&find_loc=Little+Havana%2C+Miami%2C+FL&ns=1" class="btn btn-primary">MORE</a>
            </div>
            </div>
          </div>
        </div>



        <div class="col-md-3">
          <div class="card card-inverse card-success text-center">
            <img class="card-img-top" src="/salsa.jpg" alt="Dancing">
            <div id="boostrap-havana-overrides">
            <div class="card-block">
              <h4 class="card-title">Salsa Dancing</h4>
              Best spots to practice your salsa and merengue moves!
              <br>
              <br>
              <ul>
              <li><a href="http://www.sidebarmiami.com/">Sidebar</a></li>
              <li><a href="http://www.miami.com/miami-restaurants/bar-nancy-is-little-havanas-newest-bar-157664/">Bar Nancy</a></li>
              <li><a href="https://ballandchainmiami.com/">Ball & Chain</a></li>
            </ul>
            <p>Click here for more inspiration on where to go dancing!</p>
              <a href="https://www.yelp.com/search?find_desc=Salsa+Dancing&find_loc=Little+Havana,+Miami,+FL" class="btn btn-primary">MORE</a>
            </div>
            </div>
          </div>
        </div>


        <div class="col-md-3">
          <div class="card card-inverse card-info text-center">
            <img class="card-img-top" src="outdoors.jpg" alt="Art">
              <div id="boostrap-havana-overrides">
              <div class="card-block">
              <h4 class="card-title">Outdoors</h4>
              See what the neighborhood has to offer and join in on the fun!
              <br>
              <br>
              <ul>
              <li><a href="http://www.miamiandbeaches.com/sport/maximo-gomez-park-domino-park/115777">Domino Park</a></li>
              <li><a href="http://carnavalmiami.com/event-view/calle-ocho/">Calle Ocho</a></li>
            </ul>
            <p> See what else there is to do in this historic neighborhood in Miami.<br><br>
              <a href="http://www.miamiandbeaches.com/places-to-see/little-havana/calle-ocho-domino-park" class="btn btn-primary">MORE</a>
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- JavaScripts -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script src="js/bootstrap.min.js"></script>
  <script src="js/tether.min.js"></script>
</body>
</html>

app/views/pictures/_form.html.erb
<div class="form-wrapper">
  <%= simple_form_for @pictures, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
      <%= f.input :image %>
    </div>
    <div class="form-group text-center">
      <%= f.input :caption %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
  <% end %>
</div>

<div class="text-center edit-links">
  <%= link_to "Delete Post", picture_path(@pictures), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
  |
  <%= link_to "cancel", picture_path %>
</div>

app/views/pictures/edit.html.erb
<div class="text-center">
  <%= image_tag @pictures.image.url(:medium) %>
</div>


<div id="bootstrap-edit-overrides">
<div class="form-wrapper">
  <%= simple_form_for @pictures, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
      <%= f.input :image %>
    </div>
    <div class="form-group text-center">
      <%= f.input :caption %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
  <% end %>
  <div class="text-center edit-links">
    <%= link_to "Delete Post", @pictures, method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
    |
    <%= link_to "Cancel", picture_path %>
  </div>
</div>


</div>

app/views/pictures/index.html.erb
<!-- <h1 class="display-1">Happenstance</h1>
<h2 class="tagline">Happy discoveries wherever you go...</h3>

  <img src="/logo2.png" alt="Logo"> -->

  <section class="index parallax parallax-1">
    <div class="container">
      <!-- <img src="/logo2.png" alt="Logo"> -->
      <h1>Happenstance</h1>
    </div>
  </section>
  <section class="index parallax parallax-1">
    <div class="container">
  <h2>Happy discoveries wherever you go....</h2>
</div>
</section>
<div class="heading-title">
  <p>Start your Miami exploration by scrolling through others experiences</p>
</div>
<section class="index content">
  <div class="content">
<div id="bootstrap-overrides">
<div class="picture-wrapper row">
  <% @pictures.each do |picture| %>
    <div class="picture">
      <div class="picture-head">
        <div class="name">
        <p><%= time_ago_in_words(picture.created_at) %> ago </p>
        </div>
      </div>
      <div class="image center-block">
        <%= link_to (image_tag picture.image.url(:medium), class:'img-responsive'), picture_path(picture) %>
      </div>
      <p class="caption">
        <%= picture.caption %>
      </p>

      <section id="like-button">
        <!-- <p> -->
            <a class="heart" href="#" data-id="<%= picture.id %>">
              <img src="http://i1174.photobucket.com/albums/r615/arianakv/409001-200_zpsl4iralyh.png" alt="heart">
            </a>
            <div id="p2"><%= picture.likes%><div>
        <!-- </p> -->
      </section>

    </div>
  <% end %>
</div>
</div>

<!-- Prev/Next Pages -->
<div id="link">
  <button type="button" class="btn btn-outline-info">
  <%= link_to 'Previous Page', page: @page - 1 %></button>
  <button type="button" class="btn btn-outline-info">
  <%= link_to 'Next Page', page: @page + 1 %></button>
</div>
</div>
</section>

app/views/pictures/new.html.erb
<!-- <%= simple_form_for @picture do |f| %>
  <%= f.input :image %>
  <%= f.input :caption %>
  <%= f.button :submit %>
<% end %> -->
<div id="bootstrap-new-overrides">

<div class="form-wrapper">
  <%= simple_form_for @picture, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
      <%= f.input :image %>
    </div>
    <div class="form-group text-center">
      <%= f.input :caption %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
  <% end %>
</div>
</div>

app/views/pictures/show.html.erb
<%= image_tag @pictures.image.url(:medium) %>
<div id="caption">
<%= @pictures.caption %></div>


<div class="text-center edit-links">
  <%= link_to "Back", root_path %>
  |
  <%= link_to "Edit Post", edit_picture_path(@pictures) %>
</div>